baseURL = "https://www.shanenolan.io/"
languageCode = "en-us"
title = "Shanes Blog"

[params]
  author = "Shane Nolan"
  description = "Opinions expressed are my own and not the views of my employer. Feel free to reach out to me using the following channels. "
  github = "shanenolanwit"
  linkedin = "shanenolanwit"
  email = "shane@shanenolan.io"
  utterances = "example/example.github.io"
  url = "https://www.shanenolan.io"
  keywords = "blog, google analytics"

